import "./globals.css";
import Header from "./_components/Header";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Header />
        {children}
        <footer className="text-center text-slate-400">
          &copy; {new Date().getFullYear()} KMS{" "}
        </footer>
      </body>
    </html>
  );
}
