import "./globals.css";
import Header from "./_components/Header";
import Provider from "./provider";
import { Toaster } from "@/components/ui/toaster";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Provider>
          <Header />
          <div className="container mx-auto h-[90vh]">{children}</div>
          <footer className="text-center text-slate-400">
            &copy; {new Date().getFullYear()} KMS{" "}
          </footer>
          <Toaster />
        </Provider>
      </body>
    </html>
  );
}
